# Workflow to push to npmjs. 
name: deploy2npm
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
        registry-url: https://registry.npmjs.org/

    # Publish to npm
    - name: publish
      run: cp README.md ./lib&&cd ./lib&&npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}